### ISSUE TITLE
Precompiling assets failed on Heroku only

### ISSUE THREAD

**Issue by knagode** [blocknotes/activeadmin_froala_editor#16]
```
{this.markdown.refresh(e)},plugin:"markdown"}),kt});
        61376 (function () {
        61377   'use strict'
        61378 
        61379   // --- functions -------------------------------------------------------------
        61380   function initFroalaEditors() {
        61381     $('[data-aa-froala-editor]').each(function () {
        61382       if (!$(this).hasClass('froala-editor--active')) {
           =>         let name = $(this).attr('name');
        61384         if (name) {
        61385           let options = {
        61386             quickInsertButtons: ['table', 'ol', 'ul', 'hr'],
        61387             requestHeaders: {
        61388               'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        61389             },
        61390             toolbarButtons: {
        61391               moreText: {
       ==
       /app/vendor/bundle/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:291:in `parse_result'
       /app/vendor/bundle/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:221:in `run_uglifyjs'
       /app/vendor/bundle/ruby/2.7.0/gems/uglifier-4.2.0/lib/uglifier.rb:166:in `compile'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:53:in `call'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:28:in `call'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
       /app/vendor/bundle/ruby/2.7.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
       /app/vendor/bundle/ruby/2.7.0/gems/airbrake-12.0.0/lib/airbrake/rake.rb:17:in `execute'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
```

I am trying to use this gem but am getting this error. On developement everything works however deployment on Heroku fails. It looks like there is an issue with Uglifier (on line where `let name = ...` is defined) however I am not sure how to fix this. Any idea?

**Comment by knagode** [comment]
```
config.assets.js_compressor = Uglifier.new(harmony: true)
```

Make sure to use this instad of `js_compressor = :uglify` which only supports ES5

**Comment by blocknotes** [comment]
> ```
> config.assets.js_compressor = Uglifier.new(harmony: true)
> ```
> 
> Make sure to use this instad of `js_compressor = :uglify` which only supports ES5

Thanks for your feedback @knagode
